= Meetdata

The _Meetdata_ data product describes the metered data for a single or multiple
market evaluation points (_Aansluiting_). This data product follows the EUMED
Profile, as standardised in _ISO/IEC 61968-9:2024: Interfaces for meter reading
and control_. This data product aligns with the implementation by other EU
Member States.

.Data Product
[d2,svg,theme=4]
----
grid-rows: 5
grid-columns: 3

horizontal-gap: 160
vertical-gap: 80

vars: {
  d2-config: {
    pad: 20
  }
}

MarketEvaluationPoint.class: market
MeterReading.class: enterprise
DateTimeInterval.class: enterprise

EnergyConsumer.class: grid
IntervalBlock.class: enterprise
ReadingType.class: enterprise

Location.class: enterprise
IntervalReading.class: enterprise
ReadingQuality.class: enterprise

MeterReading -> DateTimeInterval
MeterReading -> MarketEvaluationPoint
IntervalBlock -> MeterReading
IntervalBlock -> ReadingType
IntervalReading -> IntervalBlock
EnergyConsumer -> MarketEvaluationPoint
EnergyConsumer -> Location
ReadingQuality -> IntervalReading

legend: "" {
  style: {
    fill: transparent
    stroke: transparent
  }
  grid-rows: 3
  grid-columns: 2
  grid-gap: 10
  near: bottom-right
  iec61968_color: "" {
    style: {
      fill: "#d1e7c2"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61968_text: "IEC61968 (Enterprise)" {
    shape: text
  }
  iec61970_color: "" {
    style: {
      fill: "#eccfcb"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec61970_text: "IEC61970 (Grid)" {
    shape: text
  }
  iec62325_color: "" {
    style: {
      fill: "#fffbef"
      stroke: black
      stroke-width: 1
    }
    width: 10
    height: 10
  }
  iec62325_text: "IEC62325 (Market)" {
    shape: text
  }
}

classes: {
  empty: {
    label: ""
    style: {
      fill: transparent
      stroke: transparent
    }
  }
  grid: {
    style: {
      fill: "#eccfcb"
      shadow: true
    }
  }
  enterprise: {
    style: {
      fill: "#d1e7c2"
      shadow: true
    }
  }
  market: {
    style: {
      fill: "#fffbef"
      shadow: true
    }
  }
  dataset: {
    style: {
      shadow: true
    }
  }
}
----

The data is intended to be represented as a hierarchy with a
xref:schema:class/MeterReadingDataSet.adoc[`MeterReadingDataSet`] at
its root, followed by
xref:schema:class/MarketEvaluationPoint.adoc[`MarketEvaluationPoint`]s
nested inside the `MeterReadingDataSet`. Each `MarketEvaluationPoint` has one
or more xref:schema:class/MeterReading.adoc[`MeterReading`]s.

A `MeterReading` has one or more
xref:schema:class/IntervalBlock.adoc[`IntervalBlock`]s, which
defines the time period for which the
xref:schema:class/IntervalReading.adoc[`IntervalReading`]s are
applicable. A xref:schema:class/ReadingType.adoc[`ReadingType`]
defines attributes for the ``IntervalReading``s. Each `IntervalReading` can be
provided a xref:schema:class/ReadingQuality.adoc[`ReadingQuality`],
defining data quality for the `IntervalReading`.

== Use cases

This information model supports two separate use cases for providing meter
readings:

* enumeration of ``MeterReading``s for one or more ``MarketEvaluationPoint``s;
* aggregation of ``MarketEvaluationPoint``s, where the ``MeterReading``s
  describe an aggregated energy profile.

== Additional artifacts

* xref:schema:attachment$schemas/shacl/dp_meetdata.shacl.ttl[SHACL schema]
* xref:schema:attachment$examples/jsonld/dp_meetdata.example.jsonld[Example JSONLD instance data]
